version: '3.8'
services:

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    
  backend:
      build: .
      restart: always
      ports:
      - "8000:8000"
      depends_on:
        - redis

  celery:
    build: .
    command: celery -A backend worker -l info
    depends_on:
      - redis
      - backend
